    version: '3'
    services:
      next:
      
        build: .
        ports:
          - "3000:3000"
        volumes:
          - .:/app
        healthcheck:
          test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
          interval: 30s
          timeout: 10s
          retries: 5
        environment:
          - NODE_ENV=production
      nginx:
        image: nginx:alpine
        ports:
          - "80:80"
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro

        depends_on:
          - next
    