
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from './styles.module.scss'
import { Header } from "@/app/components/Header/Header";

import { createContext, Dispatch, SetStateAction, useContext, useState } from 'react';


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export type tDelete = {state: boolean, set: Dispatch<SetStateAction<boolean>>}


export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;
}>) {

 
    





  return (
    <html lang="ru">

      <body className={inter.className} >
        <main className={styles.wrapper}>
        <Header />


        
          <section className={styles.content}>
            {children}
          </section>

        </main>

        </body>
    </html>
  );
}
